input_training_x: /scratch/user/yjyang027/open-problems-multimodal/multi_train_x.h5ad
input_training_y: /scratch/user/yjyang027/open-problems-multimodal/multi_train_y.h5ad
input_test_x: /scratch/user/yjyang027/open-problems-multimodal/multi_test_x.h5ad
input_preprocessor_x: /scratch/user/yjyang027/open-problems-multimodal/multi_preprocessor_x.pkl
input_pps_training_x: /scratch/user/yjyang027/open-problems-multimodal/multi_train_x_preprocessed.npy
input_pps_test_x: /scratch/user/yjyang027/open-problems-multimodal/multi_test_x_preprocessed.npy
output_dir: /scratch/user/yjyang027/open-problems-multimodal/multi_ml_results