model: gbr
fs_name: skb
fs_estimator: f
ftr__k:
  type: i
  lo: 32
  hi: 512
regr__loss:
  type: c
  choices:
    - squared_error
    - absolute_error
    - huber
    - quantile
regr__learning_rate:
  type: l
  lo: 1e-8
  hi: 1e-1
regr__n_estimators:
  type: i
  lo: 1000
  hi: 20000
regr__subsample:
  type: f
  lo: 0.1
  hi: 1.0
regr__criterion:
  type: c
  choices:
    - squared_error
    - friedman_mse
    - squared_error
regr__min_samples_split:
  type: i
  lo: 2
  hi: 5000
regr__min_samples_leaf:
  type: i
  lo: 2
  hi: 5000
regr__max_depth:
  type: i
  lo: 1
  hi: 50
regr__max_features:
  type: c
  choices:
    - auto
    - log2
    - sqrt
regr__alpha:
  type: f
  lo: 0.1
  hi: 1.0
regr__random_state:
  type: i
  lo: 1
  hi: 1