model: svr
fs_name: skb
fs_estimator: f
ftr__k:
  type: i
  lo: 32
  hi: 512
regr__coef0:
  type: f
  lo: 0
  hi: 1000
regr__kernel:
  type: c
  choices:
    - linear
    - poly
    - rbf
    - sigmoid
regr__C:
  type: f
  lo: 1e-4
  hi: 1e4