model: dtr
fs_name: skb
fs_estimator: f
ftr__k:
  type: i
  lo: 32
  hi: 512
regr__max_depth:
  type: i
  lo: 1
  hi: 50
regr__min_samples_split:
  type: i
  lo: 2
  hi: 5000
regr__min_samples_leaf:
  type: i
  lo: 2
  hi: 5000
regr__criterion:
  type: c
  choices:
    - squared_error
    - friedman_mse
    - absolute_error
    - poisson
regr__min_weight_fraction_leaf:
  type: f
  lo: 0.1
  hi: 0.9
regr__max_features:
  type: c
  choices:
    - auto
    - log2
    - sqrt
regr__max_leaf_nodes:
  type: i
  lo: 10
  hi: 100