model: rfr
n_estimators:
  type: i
  lo: 1000
  hi: 3000
criterion:
  type: c
  choices:
    - squared_error
    - absolute_error
    - poisson
max_depth:
  type: i
  lo: 1
  hi: 50
min_samples_split:
  type: i
  lo: 2
  hi: 5000
min_samples_leaf:
  type: i
  lo: 2
  hi: 5000