X_train_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/cite_train_x_hvg3k.h5ad
y_train_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/cite_train_y_raw.h5ad
X_test_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/cite_test_x_hvg3k.h5ad
y_test_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/cite_test_y_raw.h5ad
model_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/totalVI_results/model
result_dir_pth: C:/Users/user/PycharmProjects/Multimodal_22/data/cite_seen_2/totalVI_results/
batch_key: week
mem_file_name: mem_profile.txt
name: totalVI