input_training_x: /scratch/user/yjyang027/open-problems-multimodal/train_multi_inputs.h5
input_training_y: /scratch/user/yjyang027/open-problems-multimodal/train_multi_targets.h5
input_preprocessor_x: /scratch/user/yjyang027/open-problems-multimodal/multi_preprocessor_x.pkl
input_test_x: /scratch/user/yjyang027/open-problems-multimodal/test_multi_inputs.h5
output_dir: /scratch/user/yjyang027/open-problems-multimodal/multi_ml_results