input_training_x: /mnt/c/Users/qwert/PycharmProjects/Multimodal_22/data/toy_x_train.h5ad
input_training_y: /mnt/c/Users/qwert/PycharmProjects/Multimodal_22/data/toy_y_train.h5ad
input_test_x: /mnt/c/Users/qwert/PycharmProjects/Multimodal_22/data/toy_x_test.h5ad
output_dir: /mnt/c/Users/qwert/PycharmProjects/Multimodal_22/data/test_ml_results